export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/Ordinant-ai/ordinant-ai-extension",
	GITHUB_DISCUSSIONS: "https://github.com/Ordinant-ai/ordinant-ai-extension/discussions",
	DISCORD: "https://discord.gg/roocode",
	REDDIT: "https://reddit.com/r/RooCode",
	X: "https://x.com/roocode",
	LINKEDIN: "https://www.linkedin.com/company/roo-code",
	TIKTOK: "https://www.tiktok.com/@roo.code",
	BLUESKY: "https://bsky.app/profile/roocode.bsky.social",
	YOUTUBE: "https://www.youtube.com/@RooCodeYT",
	DOCUMENTATION: "https://docs.ordinant.ai",
	CAREERS: "https://careers.ordinant.ai",
	ISSUES: "https://github.com/Ordinant-ai/ordinant-ai-extension/issues",
	FEATURE_REQUESTS: "https://github.com/Ordinant-ai/ordinant-ai-extension/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/Ordinant-ai/ordinant-ai-extension/discussions",
	CHANGELOG: "https://github.com/Ordinant-ai/ordinant-ai-extension/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/Ordinant-ai/ordinant-ai-extension/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.ordinant.ai/community",
	TUTORIALS: "https://docs.ordinant.ai/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.roo-cline",
	SECURITY: "https://trust.ordinant.ai",
	EVALS: "https://ordinant.ai/evals",
	BLOG: "https://blog.ordinant.ai",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@RooCodeYT/podcasts",
	FAQ: "https://ordinant.ai/#faq",
	TESTIMONIALS: "https://ordinant.ai/#testimonials",
	CLOUD_APP_LOGIN: "https://app.ordinant.ai/sign-in",
	CLOUD_APP_SIGNUP: "https://app.ordinant.ai/sign-up",
	CLOUD_APP_SIGNUP_HOME: "https://app.ordinant.ai/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_SIGNUP_PRO: "https://app.ordinant.ai/sign-up?redirect_url=/cloud-agents/setup",
	SUPPORT: "mailto:support@ordinant.ai",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
}
